G7_COUNTRIES = [
    'France',
    'Canada',
    'Germany',
    'Italy',
    'Japan',
    'UK',
    'USA'
]

EUROPE = [
    'Russia',
    'Spain',
    'UK',
    'Italy',
    'Germany',
    'France',
    'Sweden',
    'Belarus',
    'Belgium',
    'Ukraine',
    'Netherlands',
    'Portugal',
    'Poland',
    'Romania',
    'Switzerland',
    'Ireland',
    'Moldova',
    'Serbia',
    'Austra',
    'Czechia',
    'Denmark',
    'Norway',
    'North Macedonia',
    'Bulgaria',
    'Bosnia and Herzegovina',
    'Finland',
    'Luxembourg',
    'Hungary',
    'Croatia',
    'Greece',
    'Albania',
    'Estonia',
    'Slovakia',
    'Iceland',
    'Lithuania',
    'Slovenia',
    'Montenegro',
    'Latvia',
    'Andorra',
    'San Marino',
    'Malta',
    'Moncao',
    'Liechtenstein'
]

BENS_COUNTRIES = [
    'USA',
    'Denmark',
    'Germany',
    'Norway',
    'Finland',
    'New Zealand',
    'Canada'
]

US_STATES = [
    'New York',
    'California',
    'Florida',
    'Texas',
    'New Jersey',
    'Illinois',
    'Arizona',
    'Georgia',
    'Massachusetts',
    'Pennsylvania',
    'North Carolina',
    'Louisiana',
    'Michigan',
    'Maryland',
    'Virginia',
    'Tennessee',
    'Ohio',
    'South Carolina',
    'Alabama',
    'Indiana',
    'Connecticut',
    'Washington',
    'Minnesota',
    'Mississippi',
    'Wisconsin',
    'Colorado',
    'Iowa',
    'Missouri',
    'Nevada',
    'Utah',
    'Arkansas',
    'Oklahoma',
    'Nebraska',
    'Kansas',
    'Kentucky',
    'Rhode Island',
    'New Mexico',
    'Oregon',
    'Delaware',
    'Idaho',
    'District of Columbia',
    'South Dakota',
    'New Hampshire',
    'North Dakota',
    'West Virginia',
    'Maine',
    'Montana',
    'Wyoming',
    'Alaska',
    'Vermont',
    'Hawaii'
]

ALL_COUNTRIES_DF_HEADERS = [
        'Rank',
        'Country/Entity',
        'Total Cases',
        'New Cases',
        'Total Deaths',
        'New Deaths',
        'Total Recovered',
        'New Recovered',
        'Active Cases',
        'Serious/Critical',
        'Tot Cases per 1M pop',
        'Deaths per 1M pop',
        'Total Tests',
        'Tests per 1M pop',
        'Population',
        'Continent',
        '1 Case every X ppl',
        '1 Death every X ppl',
        '1 Test every X ppl'
]

US_STATES_DF_HEADERS = [
        'State',
        'Total Cases',
        'New Cases',
        'Total Deaths',
        'New Deaths',
        'Active Cases',
        'Tot Cases per 1M pop',
        'Deaths per 1M pop',
        'Total Tests',
        'Tests per 1M pop',
]